# Generated by Django 3.1.7 on 2022-11-10 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('Agent_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Agent_First_Name', models.CharField(max_length=15)),
                ('Agent_Last_Name', models.CharField(max_length=15)),
                ('Agent_Email', models.EmailField(max_length=254)),
                ('Agent_Cell_Phone', models.CharField(max_length=15)),
                ('Agent_Home_address', models.CharField(max_length=50)),
                ('Agent_City', models.CharField(max_length=15)),
                ('Agent_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Agent_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AmountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Address', models.CharField(max_length=50)),
                ('Property_City', models.CharField(max_length=15)),
                ('Property_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Property_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Property_Seller_Name', models.CharField(max_length=15)),
                ('Property_Buyer_Name', models.CharField(max_length=15)),
                ('Property_Final_Price', models.IntegerField()),
                ('Property_Closing_Date', models.DateField(default=django.utils.timezone.now)),
                ('Poperty_Short_Sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_Bank_Name', models.CharField(max_length=15)),
                ('Agent_address', models.CharField(max_length=50)),
                ('Agent_City', models.CharField(max_length=15)),
                ('Agent_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Agent_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Agent_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
