# Generated by Django 3.1.7 on 2022-12-02 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('Agent_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Agent_First_Name', models.CharField(max_length=15)),
                ('Agent_Last_Name', models.CharField(max_length=15)),
                ('Agent_Email', models.EmailField(max_length=254)),
                ('Agent_Cell_Phone', models.CharField(max_length=15)),
                ('Agent_Home_address', models.CharField(max_length=50)),
                ('Agent_City', models.CharField(max_length=15)),
                ('Agent_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Agent_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AmountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('amount', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('count', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('completed_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Broker_CompanyName', models.CharField(max_length=30)),
                ('Broker_address', models.CharField(max_length=50)),
                ('Broker_City', models.CharField(max_length=15)),
                ('Broker_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Broker_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Company_Cell_Phone', models.CharField(max_length=15)),
                ('BrokerFirst_Name', models.CharField(max_length=15)),
                ('Broker_Last_Name', models.CharField(max_length=15)),
                ('Broker_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingCompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closing_Company', models.CharField(max_length=20)),
                ('Escrow', models.CharField(max_length=20)),
                ('ClosingCompany_address', models.CharField(max_length=50)),
                ('ClosingCompany_city', models.CharField(max_length=50)),
                ('ClosingCompany_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('ClosingCompany_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('ClosingCompany_Cell_Phone', models.CharField(max_length=15)),
                ('ClosingCompany_Contact', models.CharField(max_length=20)),
                ('ClosingCompany_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=40)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Address', models.CharField(max_length=50)),
                ('Property_City', models.CharField(max_length=15)),
                ('Property_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Property_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Property_Seller_Name', models.CharField(max_length=15)),
                ('Property_Buyer_Name', models.CharField(max_length=15)),
                ('Property_Final_Price', models.IntegerField()),
                ('Property_Closing_Date', models.DateField(default=django.utils.timezone.now)),
                ('Poperty_Short_Sale', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RemainingFormRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrokerRecordOfCompany', models.CharField(max_length=5)),
                ('OpenAdvanceswihOther', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInformation_AgentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Net_Commission', models.IntegerField()),
                ('Selling_or_Listing', models.CharField(max_length=15)),
                ('Transaction_completein_12months', models.IntegerField()),
                ('Pedning_Transaction', models.IntegerField()),
                ('Non_pending_Transaction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_Bank_Name', models.CharField(max_length=15, null=True)),
                ('Agent_Statement_Address', models.CharField(max_length=15, null=True)),
                ('Account_number', models.IntegerField(null=True)),
                ('Routing', models.CharField(max_length=15, null=True)),
                ('Account_Holder_Name', models.CharField(max_length=50, null=True)),
                ('Agent_Account_type', models.CharField(max_length=50, null=True)),
                ('Agent_Statement_City', models.CharField(max_length=15, null=True)),
                ('Agent_Statement_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Agent_Statement_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Agent_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
