# Generated by Django 3.1.7 on 2022-12-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingformrecords',
            name='OpenAdvanceswihOther',
            field=models.CharField(max_length=5),
        ),
    ]
