# Generated by Django 3.1.7 on 2022-11-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=40)),
                ('Message', models.TextField()),
            ],
        ),
    ]
