# Generated by Django 3.1.7 on 2022-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221201_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountrequest',
            name='amount',
            field=models.CharField(max_length=5),
        ),
    ]
