# Generated by Django 3.1.7 on 2022-11-14 07:03

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_basicform1record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Broker_CompanyName', models.CharField(max_length=30)),
                ('Broker_address', models.CharField(max_length=50)),
                ('Broker_City', models.CharField(max_length=15)),
                ('Broker_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Broker_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Company_Cell_Phone', models.CharField(max_length=15)),
                ('BrokerFirst_Name', models.CharField(max_length=15)),
                ('Broker_Last_Name', models.CharField(max_length=15)),
                ('Broker_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingCompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closing_Company', models.CharField(max_length=20)),
                ('Escrow', models.CharField(max_length=20)),
                ('ClosingCompany_address', models.CharField(max_length=50)),
                ('ClosingCompany_city', models.CharField(max_length=50)),
                ('ClosingCompany_State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('ClosingCompany_Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('ClosingCompany_Cell_Phone', models.CharField(max_length=15)),
                ('ClosingCompany_Contact', models.CharField(max_length=20)),
                ('ClosingCompany_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RemainingFormRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrokerRecordOfCompany', models.CharField(max_length=5)),
                ('OpenAdvanceswihOther', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInformation_AgentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Net_Commission', models.IntegerField()),
                ('Selling_or_Listing', models.BooleanField(default=True)),
                ('Transaction_completein_12months', models.IntegerField()),
                ('Pedning_Transaction', models.IntegerField()),
                ('Non_pending_Transaction', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BasicForm1Record',
        ),
        migrations.RenameField(
            model_name='agentbankdetails',
            old_name='Agent_address',
            new_name='Agent_type',
        ),
    ]
