# Generated by Django 3.1.7 on 2022-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221201_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountrequest',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
