# Generated by Django 3.1.7 on 2022-12-01 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221201_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('count', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('completed_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
