# Generated by Django 4.0.1 on 2022-11-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_agentbankdetails_agent_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentbankdetails',
            name='Agent_ID',
        ),
        migrations.AddField(
            model_name='agentbankdetails',
            name='Agent_Bank_Name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
