# Generated by Django 4.0.1 on 2022-11-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_agentbankdetails_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankdetails',
            name='Agent_Statement_Address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
