# Generated by Django 4.0.1 on 2022-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_agentbankdetails_agent_statement_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankdetails',
            name='Account_number',
            field=models.IntegerField(null=True),
        ),
    ]
