# Generated by Django 4.0.1 on 2022-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_agentbankdetails_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankdetails',
            name='Account_Holder_Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
