# Generated by Django 4.0.1 on 2022-11-20 04:16

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_agentbankdetails_account_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankdetails',
            name='Agent_Account_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentbankdetails',
            name='Agent_Statement_City',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agentbankdetails',
            name='Agent_Statement_State',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='agentbankdetails',
            name='Agent_Statement_Zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
