# Generated by Django 4.0.1 on 2022-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_agentbankdetails_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_greement', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
