# Generated by Django 3.1.7 on 2022-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20221122_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AlterField(
            model_name='salesinformation_agentdetail',
            name='Selling_or_Listing',
            field=models.CharField(max_length=15),
        ),
    ]
